import React, { useState } from 'react';
import { FileText, Download, Filter, Search, FileBarChart, FileSpreadsheet, Sparkles, ArrowUpRight, Eye } from 'lucide-react';
import toast from 'react-hot-toast';

const Reports = () => {
  const [filter, setFilter] = useState('All');

  const reports = [
    { id: 'REP-001', title: 'Annual Workforce Report', desc: 'Headcount, turnover, and retention analysis', date: 'Q2 2026', type: 'PDF', author: 'System' },
    { id: 'REP-002', title: 'Payroll Distribution', desc: 'Site-by-site cost breakdown', date: 'June 2026', type: 'Excel', author: 'AI Agent' },
    { id: 'REP-003', title: 'Diversity & Inclusion', desc: 'Gender, age pyramid, inclusion metrics', date: 'Q2 2026', type: 'PDF', author: 'System' },
    { id: 'REP-004', title: 'Training ROI Summary', desc: 'Investment vs. impact analysis', date: 'H1 2026', type: 'PDF', author: 'System' },
    { id: 'REP-005', title: 'Retention Curve Analysis', desc: 'Historical retention by department', date: 'June 2026', type: 'Excel', author: 'AI Agent' },
    { id: 'REP-006', title: 'Executive Board Pack', desc: 'Full strategic HR overview bundle', date: 'Q2 2026', type: 'Bundle', author: 'Alex Mercer' },
  ];

  const filteredReports = filter === 'All' ? reports : reports.filter(r => r.type === filter);

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-6xl mx-auto">
      
      {/* HEADER */}
      <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-4 border-b border-slate-200/60 pb-6">
        <div>
          <p className="text-sm font-medium text-slate-500 mb-1">Data & Analytics</p>
          <h1 className="text-3xl font-bold text-slate-800 tracking-tight">Compliance Reports</h1>
        </div>
        <div className="flex gap-3">
          <button onClick={() => toast.success('AI Report Generator opened')} className="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg text-sm font-bold transition-all shadow-sm flex items-center gap-2">
            <Sparkles size={16} />
            <span>Request AI Report</span>
          </button>
        </div>
      </div>

      {/* TOOLBAR */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex items-center gap-1 bg-slate-100 rounded-lg p-1 w-full sm:w-auto overflow-x-auto">
          {['All', 'PDF', 'Excel', 'Bundle'].map(tab => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-4 py-1.5 rounded-md text-xs font-bold transition-all whitespace-nowrap ${
                filter === tab
                  ? 'bg-white text-slate-800 shadow-sm'
                  : 'text-slate-500 hover:text-slate-700'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
        <div className="relative w-full sm:w-80">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
          <input 
            type="text" 
            placeholder="Search reports by title or keyword..." 
            className="w-full pl-9 pr-4 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"
          />
        </div>
      </div>

      {/* TABLE */}
      <div className="bg-white rounded-xl border border-slate-200/60 shadow-sm overflow-x-auto">
        <table className="w-full text-sm text-left">
          <thead className="bg-slate-50/50 text-xs text-slate-500 font-medium border-b border-slate-100">
            <tr>
              <th className="py-3 px-4 font-medium">Document Name</th>
              <th className="py-3 px-4 font-medium">Period</th>
              <th className="py-3 px-4 font-medium">Type</th>
              <th className="py-3 px-4 font-medium">Generated By</th>
              <th className="py-3 px-4 font-medium text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {filteredReports.map((report) => (
              <tr key={report.id} className="hover:bg-slate-50 transition-colors group">
                <td className="py-4 px-4">
                  <div className="flex items-center gap-3">
                    <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                      report.type === 'PDF' ? 'bg-red-50 text-red-500' :
                      report.type === 'Excel' ? 'bg-green-50 text-green-600' :
                      'bg-purple-50 text-purple-600'
                    }`}>
                      {report.type === 'Excel' ? <FileSpreadsheet size={16} /> : <FileBarChart size={16} />}
                    </div>
                    <div>
                      <div className="font-bold text-slate-800 text-sm">{report.title}</div>
                      <div className="text-[11px] text-slate-500 max-w-xs truncate">{report.desc}</div>
                    </div>
                  </div>
                </td>
                <td className="py-4 px-4">
                  <div className="text-xs font-medium text-slate-700">{report.date}</div>
                </td>
                <td className="py-4 px-4">
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md border ${
                    report.type === 'PDF' ? 'bg-red-50 text-red-700 border-red-100' :
                    report.type === 'Excel' ? 'bg-green-50 text-green-700 border-green-100' :
                    'bg-purple-50 text-purple-700 border-purple-100'
                  }`}>
                    {report.type}
                  </span>
                </td>
                <td className="py-4 px-4 text-xs font-medium text-slate-600">
                  {report.author === 'AI Agent' ? (
                    <span className="flex items-center gap-1 text-primary-600"><Sparkles size={12} /> {report.author}</span>
                  ) : (
                    report.author
                  )}
                </td>
                <td className="py-4 px-4 text-right">
                  <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => toast('Opening document preview...')} className="px-2 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-md transition-colors" title="Preview">
                      <Eye size={14} />
                    </button>
                    <button onClick={() => toast.success('Download started')} className="px-2 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-900 rounded-md transition-colors border border-slate-200" title="Download">
                      <Download size={14} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

    </div>
  );
};

export default Reports;
